### ISSUE TITLE
Add reporting functionality for text from Bebyggelseregistret

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#11]
Add a button/icon in the lower right corner that launches an email to bebyggelseregistret@raa.se with subject line "Angående 'item.label' " and starting text: 
"I kyrkan med id: 'item.kulturarvsdata' har jag följande att anmärka 

Mejlet har skapats från webbplatsen kyrksok.se"
Where item.label and item.kulturarvsdata is variables for the current church one is looking at.

**Comment by Abbe98** [comment]
So right now this could be done as a mailto-link, but if we want the automatically created text it would be a server thing.

**Comment by Ainali** [comment]
You can't add the auto-text in the mailto link through javascript? Or do you just think that is a bad idea?

**Comment by Abbe98** [comment]
I have never done it, you could look into it.

**Comment by rjakobsson** [comment]
On it!

**Comment by Abbe98** [comment]
Planed on 09/11
https://github.com/Abbe98/open-source-sprints/projects/1?fullscreen=true

**Comment by Abbe98** [comment]
I'm not sure the link works in all browsers/operating systems.
