### ISSUE TITLE
Style the map button

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#16]
Change the styling of the map button to be the same as in the wireframe on [bit.ly/trådmodell](bit.ly/trådmodell)

**Comment by Ainali** [comment]
Here is an icon. https://commons.wikimedia.org/wiki/File:Map_geo.svg
If used, add attribution in [about.html](https://github.com/Kyrkosok/web-client/blob/master/src/about.html)

**Comment by Antignote** [comment]
See my PR https://github.com/Kyrkosok/web-client/pull/29 :)
