### ISSUE TITLE
Upload images to Wikimedia Commons

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#23]
For a user that is at a church, he should be able to upload images for it. Add an upload button.

The URL for the button should be 
https://commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=kyrksok&id=item.kulturarvsdata&categories=item.commons

Where item.commons and item.kulturavsdata is variables for the current church.

**Comment by rjakobsson** [comment]
On it!

**Comment by Abbe98** [comment]
Tracked over at Kyrkosok/database#5, the task is combined with mapping parts of the Swedish WLM Databse against Wikidata(made sense to me).

**Comment by Abbe98** [comment]
https://kyrksok.se/Q10496884 "ladda upp bild" under kyrkans namn.
