### ISSUE TITLE
Add campaign on Wikimedia Commons to recieve images

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#24]
We need to setup a [campaign](https://commons.wikimedia.org/wiki/Commons:Upload_campaigns) on Wikimedia Commons. We have commons cat, and id for the template bbr in the url-parameter we use (from issue #23). A good name for the campaign would be **kyrksok**.

**Comment by Ainali** [comment]
@lokal-profil Can you help us with the campaign? It is very similar to the Wiki Loves Monuments campaigns (all objects are churches).

**Comment by Abbe98** [comment]
This is currently a blocker for #23 and #25

**Comment by lokal-profil** [comment]
OK so what I would need is for you to fill out the missing bits in the template below (you can use [wlm-se-bbr](https://commons.wikimedia.org/w/index.php?title=Campaign:wlm-se-bbr&action=edit) and [ÖDOK](https://commons.wikimedia.org/w/index.php?title=Campaign:%C3%96DOK&action=edit) as a guide).

Also will you always provide bbr complex ids (anläggningsid) or might it be building ids instead?
- `<default category>` is optional (the images will automatically be categorised as uploaded through the campaign).
- `<title>` is the text which would be displayed when you visit the Campaign to look at the uploaded images.
- `<header>` and `<thanks>` are displayed when/after you are uploading images. These are normally i18n enabled templates.
- `<bbr id label>` and `<bbr type label>`: Helper labels explaining what the contents in the fields should be (and any limitations). See e.g. [Mwe-upwiz-campaigns-wlm-se-bbr-id](https://commons.wikimedia.org/wiki/MediaWiki:Mwe-upwiz-campaigns-wlm-se-bbr-id)

The template below restricts the license choice to simplify the process. Let me know if that is not what you want

```
{
    "enabled": true,
    "title": "<title>",
    "display": {
        "headerLabel": "<header>",
        "thanksLabel": "<thanks>"
    },
    "defaults": {
        "categories": [
            "<default category>"
        ]
    },
    "licensing": {
        "ownWorkDefault": "own",
        "ownWork": {
            "licenses": [
                "cc-by-sa-4.0"
            ]
        }
    },
    "fields": [
        {
            "wikitext": "{{BBR|1=$1",
            "label": "<bbr id label>",
            "required": true
        },
        {
            "wikitext": "|2=$1}}",
            "label": "<bbr type label>",
            "required": true
        }
    ],
    "tutorial": {
        "skip": true
    }
}
```

**Comment by Abbe98** [comment]
Actually kyrksok sometimes have complex id;s and sometimes just building
ones...

2016-10-31 12:59 GMT+01:00 André Costa notifications@github.com:

**Comment by lokal-profil** [comment]
Then you would need to pass both the id and the type ("a" or "b") to the campaign (I did a similar thing in the ÖDOK campaign.

**Comment by Abbe98** [comment]
For the new URI;s that's not a issue but for the old ones I might need to
add a type column to the database and retrive it from the indexing script...

2016-10-31 15:02 GMT+01:00 André Costa notifications@github.com:

**Comment by lokal-profil** [comment]
I updated the template to take into account the two parts of the id. What I would need from you to take this further are all of the `<entries>`. They should be either in English or better yet multilingual.

**Comment by Abbe98** [comment]
`<entries>` would be the filename?

I will start distinguish building and facility id;s in different columns when indexing, it's probably a few hours of work because I would like to improve the coverage of both types in Wikidata too. It would make it easier to support both this and WLM in the future...

**Comment by lokal-profil** [comment]
Sorry with `<entries>` I meant every single entry in my template above which I surrounded by `<>` brackets. So the help texts/titles/banners etc. to show to users.

**Comment by Abbe98** [comment]
Okey, I'm afraid this is a task for my winter holidays or a very long train trip...

**Comment by Ainali** [comment]
Jag tror att vi kan hoppa över i18n-mallade meddelanden just nu eftersom att det enda stället vi har länkarna är från ett gränssnitt på svenska. När vi utökar det till fler språk bör vi såklart fixa det. Här kommer mitt försök till entries.
"title": Kyrkor
"headerLabel": Ladda upp dina bilder på kyrkor.
"thanksLabel": Tack för att du har laddat upp kyrkbilder till Wikimedia Commons!
"categories": Images uploaded through Kyrksök

**Comment by lokal-profil** [comment]
Good if you can write something for the last two then I'll try to put it up later this week.

**Comment by Abbe98** [comment]
I guess `<bbr id label>` and `<bbr type label>` could be equal to the ones in WLM?

**Comment by lokal-profil** [comment]
That was my first thought but wlm assumes "anläggning" and so there is only one parameter which explicitly mentions that.

**Comment by Ainali** [comment]
Ping @lokal-profil: do you need any more information to complete this?

**Comment by Abbe98** [comment]
Closed by [T299915](https://phabricator.wikimedia.org/T299915).
