### ISSUE TITLE
What to include in the timeline

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#30]
This is a general discussion issue to figure out what to include in the timeline of the church. We could probably introduce this in several different steps. The first and most easiest steps would be to include data that is directly in the object on Wikidata about the church (without looking at objects that are connected to the church). Here comes a listing of what could go into that first phase. Please add more ideas as comments.  
- P571 (inception)
- P576 (dissolved or abolished)
- P729 (service entry)
- P730 (service retirement)
- P793 (significant event) (with dates in qualifiers, P580 (start time), P582 (end time) and P585 (point in time))
- P1619 (date of official opening)
- P2669 (discontinued date)

Next step is to figure out how to present this in an interesting and user friendly way.

**Comment by Ainali** [comment]
To go one level deeper and add a lot more dates, we could add information about the persons listed in the church object. Here comes a first listing of suggestions:

- P84 (architect)
- P112 (founder)
- P138 (named after)
- P542 (officially opened by)

For all these we could add: 
- P569 (date of birth)
- P570 (date of death)
- P793 (significant event) (with dates in qualifiers, P580 (start time), P582 (end time) and P585 (point in time))
- P800 (notable work) (with dates in qualifiers, P580 (start time), P582 (end time) and P585 (point in time))

In the future, these might be useful too, but right now there are no churches in Sweden that uses these properties:

- P88 (commissioned by)
- P589 (sponsor) 

Also P193 (main building contractor) could be interesting, but it is a bit more complex as it contains both corporations and persons.

**Comment by Ainali** [comment]
Even though it is quite a lot different from the sketches, I suggest to use [TimelineJS](https://timeline.knightlab.com/index.html) which support loading events from JSON which sounds like it fits well with your thoughts @Abbe98, or what do you think?

**Comment by Abbe98** [comment]
It would save me time :-)

2016-12-06 14:41 GMT+01:00 Jan Ainali <notifications@github.com>:

**Comment by Abbe98** [comment]
@Ainali from your perspective does it make sense to import all this data into Wikidata?

**Comment by Ainali** [comment]
@Abbe98 Yes, but I was mostly thinking of using the data that is already in there. I am trying to figure out what data is available in a structured format that even could be imported.

**Comment by Abbe98** [comment]
@Ainali Okey, some Wikidata folks would be against merging another dataset but I personally thinks it adds value.

**Comment by Ainali** [comment]
@Abbe98 There are datasets imported to Wikidata all the time and there is even a [dedicated page](https://www.wikidata.org/wiki/Wikidata:Partnerships_and_data_imports) for new partnerships. If something was resisted it probably had some specific reasons rather than a general stop of imports.

**Comment by Ainali** [comment]
I did not realize that the event data in BBR was available in a structured format through K-samsök. But after looking at [an example](http://kulturarvsdata.se/raa/bbr/jsonld/21400000440954) I realize it is quite rich data. Importing it into Wikidata would be great, but requires extensive mapping of event types and persons (and probably some groundwork in creating appropriate items first). It might be more straightforward just using the data from BBR directly.

**Comment by Abbe98** [comment]
My intention is to import all the events for objects which has a item in
Wikidata. I will take a dump of BBR directly instead of using K-Samsök for
this task. It's quite a easy task but mappings and testing makes it time
consuming.

I intend to map the Swedish WLM against Wikidata over the upcoming holidays
this will add add plenty of BBR statements to Wikidata items. Not sure when
I will get the time to import the event data, I'm running out of school
holidays...

2016-12-14 12:40 GMT+01:00 Jan Ainali <notifications@github.com>:

**Comment by Ainali** [comment]
@Abbe98 If you provide a list of different values for the events in BBR, I could start the mapping. It seems like this area is a bit of a mess on Wikidata (I just made [this](http://tinyurl.com/h47folf) to visualize it a little bit), so a cleanup there would be good too, and I will try to find a few experts in construction terminology to help with that.

**Comment by Abbe98** [comment]
The event's in BBR is not relay structured data or standardized.
They are just written as "Fast inredning - orgel", "Underhåll -
målningsarbete, interiör" etc(probably written by hand).

I will extract a complete list anyway so at least the most common ones can
be mapped(I will need to update my BBR dump once I my holidays ends).

2017-01-04 12:51 GMT+01:00 Jan Ainali <notifications@github.com>:

**Comment by Abbe98** [comment]
The timeline now includes all events under P793 (significant event) if they have point in time or start time.

In practice, [this query](https://w.wiki/3JD3) is used and embedded in the ["church.html" template](https://github.com/Kyrkosok/web-client/blob/master/templates/church.html#L50).

Example: https://kyrksok.se/Q10496884.html
