### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#34]
Add a favicon, perhaps the text from the [logo](https://github.com/Kyrkosok/web-client/blob/master/src/logo.svg) need to be removed to reduce clutter.

**Comment by Abbe98** [comment]
Yep, favicon and mobile web app support is probably the next thing I will do as it's quite a small task.

**Comment by Ainali** [comment]
This code and files might perhaps do? 

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">
```

[favicons.zip](https://github.com/Kyrkosok/web-client/files/636152/favicons.zip)

**Comment by Abbe98** [comment]
There will be a bunch of other tags and images in the end I'm afraid...

2016-12-07 10:20 GMT+01:00 Jan Ainali <notifications@github.com>:
