### ISSUE TITLE
Fix column css for the search text 

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/web-client#4]
Fix the css for the search text so it does not overflow under the image when there is a lot of text. Instead it should stay in its 'column'.

**Comment by SilentFlame** [comment]
@Ainali 
I will work on this.

Not getting what exactly you mean by the above description?

**Comment by Ainali** [comment]
@SilentFlame There was just a pull request submitted for this in #7

**Comment by SilentFlame** [comment]
Cool
