### ISSUE TITLE
Search on large screens

### ISSUE THREAD

**Issue by Abbe98** [Kyrkosok/web-client#6]
Currently search results extends to the full width, this should not be the case on larger screens

**Comment by Ainali** [comment]
If screen size is 600-1024 px, I guess 600px would be a nice center column size and for even larger screens perhaps 50% for the center is alright?

**Comment by Abbe98** [comment]
@Ainali you are the designer :wink:

**Comment by Irvandoval** [comment]
My proposal  #12

**Comment by ghost** [comment]
A little new to this, so forgive me if I did this wrong. Here is mine, which is slightly more concise: #27

**Comment by Abbe98** [comment]
Planed on 09/11
https://github.com/Abbe98/open-source-sprints/projects/1?fullscreen=true
