### ISSUE TITLE
Introduce loading screen for the map

### ISSUE THREAD

**Issue by Abbe98** [Kyrkosok/web-client#9]
`church.html` displays a loading screen when loading the data, `map.html` should do the same.

**Comment by HashCode55** [comment]
I'm on it.

**Comment by Irvandoval** [comment]
#15

**Comment by Irvandoval** [comment]
I solve the issue with #15

**Comment by Abbe98** [comment]
Planed on 09/11
https://github.com/Abbe98/open-source-sprints/projects/1?fullscreen=true
